services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 256mb
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./scripts/postgres/:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

volumes:
  task-dev-data:
